# Site settings
title: Dale Palmer Jr.
footer: Dale Palmer Jr.
email: dpalmerpdx@gmail.com
description: The purpose of this site is to highlight my journey into the world of development past my experience at Epicodus. You will discover the projects that I am proud of within.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dalepalmer.github.io" # the base hostname & protocol for your site
twitter_username: Xkilr0yX
github_username:  DalePalmer
address: Portland Oregon
name: Dale Palmer Jr.
pic: 1
position: Web Developer



# Build settings
markdown: kramdown
permalink: pretty
